import dotenv from 'dotenv'

dotenv.config()

export const env = {
	NODE_ENV: process.env.NODE_ENV,
	PORT: process.env.PORT,

	ORIGIN: process.env.ORIGIN,

	JWT_SECRET: process.env.JWT_SECRET,
	JWT_LIFE_ACCESS_TOKEN: process.env.JWT_LIFE_ACCESS_TOKEN,
	JWT_LIFE_REFRESH_TOKEN: process.env.JWT_LIFE_REFRESH_TOKEN,

	LOG_LEVEL: process.env.LOG_LEVEL,

	GOOGLE_NODEMAILER_CLIENT_ID: process.env.GOOGLE_NODEMAILER_CLIENT_ID,
	GOOGLE_NODEMAILER_CLIENT_SECRET: process.env.GOOGLE_NODEMAILER_CLIENT_SECRET,
	GOOGLE_NODEMAILER_REDIRECT_ID: process.env.GOOGLE_NODEMAILER_REDIRECT_ID,
	GOOGLE_NODEMAILER_REFRESH_TOKEN: process.env.GOOGLE_NODEMAILER_REFRESH_TOKEN,
	GOOGLE_NODEMAILER_GOOGLE_USER: process.env.GOOGLE_NODEMAILER_GOOGLE_USER,

	GOOGLE_AUTH_CLIENT_ID: process.env.GOOGLE_AUTH_CLIENT_ID,
	GOOGLE_AUTH_CLIENT_SECRET: process.env.GOOGLE_AUTH_CLIENT_SECRET,
	GOOGLE_AUTH_CALLBACK_URL: process.env.GOOGLE_AUTH_CALLBACK_URL,

	MONGO_URI: `mongodb://${process.env.MONGO_HOST}:${process.env.MONGO_PORT}/${process.env.MONGO_NAME}`,

	AWS_REGION: process.env.AWS_REGION,
	AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
	AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
	AWS_S3_BUCKETS_NAME: process.env.AWS_S3_BUCKETS_NAME,
}
